# This file is used to generate a conda environment with minimal dependencies
# Only jupyter dependencies are included, and the correspoingin python version.
# Due to backports, absolute pinning is impossible.  So update this file Only as needed.

# Anaconda 4.2 includes nb_conda_kernels, which auto-installs kernelspecs
# `conda env update -f environment_jupyter.yaml` make the env and kernalspec

name: nbregtest
dependencies:
- decorator=4.0.9=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.1.2=py35_0
- ipython_genutils=0.1.0=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter_client=4.1.1=py35_0
- jupyter_core=4.0.6=py35_0
- markupsafe=0.23=py35_0
- mistune=0.7.1=py35_0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.1.0=py35_0
- path.py=8.1.2=py35_1
- pickleshare=0.5=py35_0
- pygments=2.1.1=py35_0
- pyreadline=2.1=py35_0
- python=3.5.1=4
- pyzmq=15.2.0=py35_0
- simplegeneric=0.8.1=py35_0
- tornado=4.3=py35_0
- traitlets=4.1.0=py35_0
