name: py35
dependencies:
- cycler=0.10.0=py35_0
- decorator=4.0.9=py35_0
- et_xmlfile=1.0.1=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.1.2=py35_0
- ipython_genutils=0.1.0=py35_0
- jdcal=1.2=py35_0
- jinja2=2.8=py35_0
- jpeg=8d=vc14_0
- jsonschema=2.4.0=py35_0
- jupyter_client=4.1.1=py35_0
- jupyter_core=4.0.6=py35_0
- libpng=1.6.17=vc14_1
- libtiff=4.0.6=vc14_1
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.1=py35_0
- mkl=11.3.1=0
- msvc_runtime=1.0.1=vc14_0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- nose=1.3.7=py35_0
- notebook=4.1.0=py35_0
- numpy=1.10.4=py35_0
- openpyxl=2.3.2=py35_0
- openssl=1.0.2g=vc14_0
- pandas=0.18.0=np110py35_0
- path.py=8.1.2=py35_1
- pickleshare=0.5=py35_0
- pip=8.0.3=py35_0
- pygments=2.1.1=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_5
- pyreadline=2.1=py35_0
- python=3.5.1=4
- python-dateutil=2.5.1=py35_0
- pytz=2016.3=py35_0
- pyzmq=15.2.0=py35_0
- qt=4.8.7=vc14_7
- setuptools=20.1.1=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_2
- six=1.10.0=py35_0
- tk=8.5.18=vc14_0
- tornado=4.3=py35_0
- traitlets=4.1.0=py35_0
- vs2015_runtime=14.00.23026.0=0
- wheel=0.29.0=py35_0
- xlrd=0.9.4=py35_0
- zlib=1.2.8=vc14_2
- pip:
  - et-xmlfile==1.0.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - sphinx==1.3.1
  - version-information==1.0.3
  - websockets==3.1

