# Only used for ancillary projects
name: C:\Anaconda\envs\py34
dependencies:
- msvc_runtime=1.0.1=vc10_0
- pip=8.0.3=py34_0
- python=3.4.4=2
- requests=2.9.1=py34_0
- setuptools=20.1.1=py34_0
- wheel=0.29.0=py34_0
- pip:
  - asyncio==3.4.3
  - websockets==3.0
