name: lamana_docs
dependencies:
- matplotlib                                               # seems needed for sphinx on rtd
- pandas                                                   # speeds up build
- numpy
- openpyxl
- six
- pip                                                      # try unpinned
  - nbsphinx
  - ipykernel
  - numpydoc
#  - nbsphinx==0.2.2
#  - ipykernel==4.2.2
#  - numpydoc==0.5
