name: lamana_docs
dependencies:
- python=3.5                                               # was installing py27
- matplotlib                                               # seems needed for sphinx on rtd
- pandas                                                   # speeds up build
- numpy
- openpyxl
- six
- ipykernel                                                # moved to conda 0.4.13-dev
- sphinx_rtd_theme                                         # added 0.4.13-dev
- pip:                                                     # unpinned 0.4.13-dev
  - nbsphinx
  - numpydoc
#  - nbsphinx==0.2.2
#  - ipykernel==4.2.2
#  - numpydoc==0.5
